name: Run C++ Tests
on:
  push:
    paths:
      - 'scripts/run_cpp_test.py'
      - 'src/**'
  pull_request:
    paths:
      - 'scripts/run_cpp_test.py'
      - 'src/**'
  workflow_dispatch:

jobs:
  run_cpp_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
    # Clean the output directory to avoid repeated files
    - name: Clean output directory
      run: |
        rm -rf output/* || true  # Ensure the directory is clean before running the script
        
    - name: Run C++ test script
      run: |
        python scripts/run_cpp_test.py
      shell: bash
    
    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cpp-test-output
        path: output/
        if-no-files-found: warn
    
    # Display the output to the logs
    - name: Display output
      run: |
        cat output/* || echo "No output found"
      shell: bash
    
    - name: Always succeed
      if: always()
      run: |
        echo "Job completed. Check previous steps for any errors."
        exit 0
