name: Extract Elements
on:
  push:
    paths:
      - 'scripts/extract_elements.py'
      - 'src/**'
      - 'requirements/extract_elements.txt'
  pull_request:
    paths:
      - 'scripts/extract_elements.py'
      - 'src/**'
      - 'requirements/extract_elements.txt'
  workflow_dispatch:

jobs:
  extract_elements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/extract_elements.txt
    
    - name: Run extract elements script
      run: |
        cd scripts
        python extract_elements.py
      shell: bash
    
    - name: Upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: extract-elements-output
        path: output/extract_elements_output/
    
    - name: Always succeed
      run: exit 0
