name: Run analyze_identation.py
on:
  push:
    paths:
      - 'scripts/analyze_identation.py'
      - 'src/**'
  pull_request:
    paths:
      - 'scripts/analyze_identation.py'
      - 'src/**'
  workflow_dispatch:

jobs:
  run_analyze_indentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install cpplint
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
    # Clean the output directory to avoid repeated files
    - name: Clean output directory
      run: |
        rm -rf output/* || true  # Ensure the directory is clean before running the script
        
    - name: Run analyze_identation.py
      run: |
        python scripts/analyze_identation.py
      shell: bash
    
    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: analyze_identation_report
        path: output/
        if-no-files-found: warn
    
    # Display the output to the logs
    - name: Display output
      run: |
        cat output/* || echo "No output found"
      shell: bash
    
    - name: Always succeed
      if: always()
      run: |
        echo "Job completed. Check previous steps for any errors."
        exit 0
