name: Run analyze_indentation.py
on:
  push:
    paths:
      - 'scripts/analyze_identation.py'
      - 'src/**'
  pull_request:
    paths:
      - 'scripts/analyze_identation.py'
      - 'src/**'
  workflow_dispatch:

jobs:
  run_analyze_indentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install cpplint
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
    
    - name: Run analyze_indentation.py
      run: |
        python scripts/analyze_identation.py
      shell: bash
    
    - name: Upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: analyze_indentation_report
        path: output/REPORTE_ANALISIS_INDENTACION_*.md
    
    - name: Always succeed
      if: always()
      run: |
        echo "Job completed. Check previous steps for any errors."
        exit 0
