name: Run Plagiarism Check
on:
  push:
    paths:
      - 'scripts/run_plagiarism_1.py'
      - 'src/**'
      - 'requirements/run_plagiarism_1.txt'
  pull_request:
    paths:
      - 'scripts/run_plagiarism_1.py'
      - 'src/**'
      - 'requirements/run_plagiarism_1.txt'
  workflow_dispatch:

jobs:
  run_plagiarism_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/run_plagiarism_1.txt
        python -m spacy download es_core_news_sm
        python -m nltk.downloader wordnet
    # Clean the output directory to avoid repeated files
    - name: Clean output directory
      run: |
        rm -rf output/* || true  # Ensure the directory is clean before running the script
        
    - name: Run plagiarism script
      run: |
        python scripts/run_plagiarism_1.py
      env:
        PYTHONWARNINGS: "ignore:clean_up_tokenization_spaces:FutureWarning"
      shell: bash
    
    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: plagiarism-check-output
        path: output/
        if-no-files-found: warn
    
    # Display the output to the logs
    - name: Display output
      run: |
        cat output/* || echo "No output found"
      shell: bash
    
    - name: Always succeed
      if: always()
      run: |
        echo "Job completed. Check previous steps for any errors."
        exit 0
