name: Run C++ Tests

on:
  push:
    paths:
      - 'src/**'
      - 'scripts/run_cpp_test.py'
      - 'input/**'
      - 'expected_output/**'
  pull_request:
    paths:
      - 'src/**'
      - 'scripts/run_cpp_test.py'
      - 'input/**'
      - 'expected_output/**'
  workflow_dispatch:

jobs:
  run_cpp_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    
    - name: Run C++ tests
      run: |
        python scripts/run_cpp_test.py
      shell: bash
    
    - name: Upload test results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: cpp-test-results
        path: output/REPORTE_ANALISIS_*.md
    
    - name: Always succeed
      run: exit 0
