name: Run Python and C++ Tests

on:
  push:
    paths:
      - 'scripts/**'
      - 'src/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'scripts/**'
      - 'src/**'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck g++
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download es_core_news_sm
        python -m nltk.downloader wordnet
    
    - name: Run Python scripts
      run: |
        cd scripts
        python run_plagiarism_1.py
        python extract_elements.py
        python analyze_spelling.py
        python run_cppcheck.py
        python run_cpp_test.py
      env:
        PYTHONWARNINGS: "ignore:clean_up_tokenization_spaces:FutureWarning"
      shell: bash
    
    - name: Upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: script-output
        path: output/
    
    - name: Always succeed
      run: exit 0
