name: Analyze Spelling
on:
  push:
    paths:
      - 'scripts/analyze_spelling.py'
      - 'src/**'
      - 'requirements/analyze_spelling.txt'
  pull_request:
    paths:
      - 'scripts/analyze_spelling.py'
      - 'src/**'
      - 'requirements/analyze_spelling.txt'
  workflow_dispatch:

jobs:
  analyze_spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/analyze_spelling.txt
    
    - name: Run analyze spelling script
      run: |
        python scripts/analyze_spelling.py
      shell: bash
    
    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: analyze-spelling-output
        path: output/
        if-no-files-found: warn
    
    - name: Always succeed
      if: always()
      run: |
        echo "Job completed. Check previous steps for any errors."
        exit 0
