name: Run analyze_structure.py
on:
  push:
    paths:
      - 'scripts/analyze_structure.py'
      - 'src/'
  pull_request:
    paths:
      - 'scripts/analyze_structure.py'
      - 'src/'
  workflow_dispatch:
jobs:
  run_analyze_structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
# Clean the output directory to avoid repeated files
    - name: Clean output directory
      run: |
        rm -rf output/* || true  # Ensure the directory is clean before running the script
        
    - name: Run analyze_structure.py
      run: |
        python scripts/analyze_structure.py
      shell: bash

    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: analyze_structure
        path: output/
        if-no-files-found: warn

    # Display the output to the logs
    - name: Display output
      run: |
        cat output/* || echo "No output found"
      shell: bash

    # Always succeed
    - name: Always succeed
      if: always()
      run: |
        echo "Job completed. Check previous steps for any errors."
        exit 0
