name: Run analyze_structure.py
on:
  push:
    paths:
      - 'scripts/analyze_structure.py'
      - 'src/'
  pull_request:
    paths:
      - 'scripts/analyze_structure.py'
      - 'src/'
  workflow_dispatch:
jobs:
  run_analyze_structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: Run analyze_structure.py
      run: |
        python scripts/analyze_structure.py
      shell: bash

    # Print the output to the logs instead of uploading as a zip
    - name: Display output
      run: |
        cat output/* || echo "No output found"
      shell: bash

    # Always succeed
    - name: Always succeed
      if: always()
      run: |
        echo "Job completed. Check previous steps for any errors."
        exit 0
